### ISSUE TITLE
How to used tool specifc environment variables?

### ISSUE THREAD

**Issue by adamb0403** [ArabCoders/watchstate#101]

**Comment by adamb0403** [comment]
I am trying to enable cron import and export but I cannot find where to enable the environmental variables

**Comment by adamb0403** [comment]
Thanks, also, what is the difference in usage between state:push and state:export?

**Comment by ArabCoders** [comment]
state:push command is used to push events queued via webhooks, which is the most efficient method to do watch state, as it's require less data transfer from both ends.

state:export is the more traditional way of doing sync, require more memory and data transfer, as it's inspect each individual media item. it works, but i honestly don't like it and prefer the updates via webhooks.

**Comment by adamb0403** [comment]
Cool. I'll keep that in mind. The initial import from plex and then export to emby isn't correctly changing the watched states for all media. Is this common?

**Comment by adamb0403** [comment]
Thanks, this has worked. Is there anyway to apply --ignore-date when exporting via the cron scheduler?

**Comment by ArabCoders** [comment]
> Thanks, this has worked. Is there anyway to apply --ignore-date when exporting via the cron scheduler?

No problem, There is not an official way to do so currently, however the config is flexible and this might work try this.

```
console servers:edit --key 'options.ignore-date' --set true -- server_name
```
after doing this edit the file /config/config/servers.yaml and remove the quotation marks around the `true` value.

for example once you run the command and view the config it will look like this

```yaml
  ....
  options:
    ignore-date: 'true'
  .... 
```

it should look like this


```yaml
  ....
  options:
    ignore-date: true
  .... 
```
without "`" marks. hopefully next update will fix this to allow you to set Boolean value via command like.

**Comment by adamb0403** [comment]
Nice, thanks for this. I feel bad for asking all these questions, but I do have a few more unfortunatley:

1) Does state:push execute automatically when a webhook change is detected? Or does that also need a cron schedule?

2) I understaned mark as watched/unwatched for plex does not track with webhooks, but it is also not tracking using import/export when exporting to emby/jellyfin. Is this intended?

3) Is there any support for watch progress to be synced aswell as watch states?

**Comment by ArabCoders** [comment]
No worries.



> * Does state:push execute automatically when a webhook change is detected? Or does that also need a cron schedule?

By default state:push is enabled automatically. and it queues watch state events that are received via webhooks, if webhook enabled you can run

```bash
console state:push --queue-show -vvvr
```

to see list of queued events.



> * I understaned mark as watched/unwatched for plex does not track with webhooks, but it is also not tracking using import/export when exporting to emby/jellyfin. Is this intended?


No that is not intended, i think plex does reset the date on item when you mark items as unwatched, However for mark as watched it should be picked up when state:import is run, you could mark one item as such then run state:export with `-vvr` it should show info about being state updated., and to answer the other half of your question, i think if you run with `-vvvr` you should see why the item is not being synced, most likely as i said there is probably no shared external ids. run with the flags and report back.

> * Is there any support for watch progress to be synced as well as watch states?

it's something that has been brought up lately, sadly right now i am working on re-designing the database store to fully support relative unique identifiers for tv shows. As such, once i have it working and merged into master i should be able to investigate if there is a way to do so.

**Comment by adamb0403** [comment]
Hi, I can confirm plex mark as watched tracks correctly. However plex mark as unwatched does not track on import. Any workaround for this?

Also great job on this program, much more intuitive than using trakt as I was before. i appriciate the effort you put into it :)

**Comment by ArabCoders** [comment]
Glad it's working for you, sadly this is limitation on plex part, however i try with `--force-full` flag it might sync plex unwatched state.

**Comment by ArabCoders** [comment]
As there is no more questions, I'll be closing this issue. Feel free to post any questions again on this issue if you need to.
