### ISSUE TITLE
Is it possible to bi-directional sync a plex home user to/from Jellyfin user?

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [ArabCoders/watchstate#11]
Maybe specify a home user in the config, and only use that data?

**Comment by ArabCoders** [comment]
Hi, i have to investigate if it's possible to get the user Id from plex API side, i know for sure that emby/jellyfin works directly with user Ids, however plex API is strange beast so far, the tool can sync both ways. I'll let you know soon

**Comment by ArabCoders** [comment]
Ok after quick looking, it seems it's possible to do for plex managed users, as the only difference is the X-Plex-token for each user, so create new managed user, and log in using that user, extract the token and use it. 

However this tool is not equipped to deal with mutli-user setup as the database design assumes one user for all servers, dont fret though you can run container for each user until we can overcome this limitations in later stages.
