### ISSUE TITLE
Feature Request: Multi User Support

### ISSUE THREAD

**Issue by ggogel** [ArabCoders/watchstate#136]
Hello,

I'm running emby and jellyfin side by side. I'm currently syncing watch states between them with the Trakt plugin but I want to move away from it since it's a 3rd party tool, slow, tedious to manage and prone to errors. I was about to implement my own solution but found this tool. I read in the FAQ that syncing multiple users is only possible by running multiple container instances. I currently have 20+ users and running one container for each user seems a bit overkill to me. Are there any plans to support multiple users in a single instance? It would help me and I guess many others a lot.

**Comment by ArabCoders** [comment]
It's possible to run one container for many users but the setup required is kinda complicated you have to switch WS_DATA_PATH for each user if you are just doing scheduled tasks, its gets more complicated for web hooks as you have to change context in http layer as well. 

Right now I'm focusing on stabilizing the codebase once that done i will try to tackle this issue i know many users want this feature.

**Comment by ggogel** [comment]
Hi,

Thanks for your fast response. Syncing with the scheduled task is sufficient for me. The data doesn't need to be updated in real-time. Can you provide me with instructions on how to set a different WS_DATA_PATH for each user?

**Comment by ArabCoders** [comment]
On top of my head right now, You dont use docker-compose for multi-user instead rely on directly running the commands.

very rough and primitive way of doing it is the following create new directory lets say `/home/user/watchstate` inside that directory create new file called `env`. put the following environment keys

```env
WS_DISABLE_HTTP=1
WS_DISABLE_CRON=1
WS_DISABLE_CACHE=1
```

inside the same directory create new user data path for each user. For example, 

```bash
$ mkdir -p /home/user/watchstate/config/{user1,user2,user3} 
```

once that done the you need to create the actual config for each user, to do so run the following command, be mindful you need to change the `-v /home/user/watchstate/config/user1` to match the user data path

```bash
docker run --env-file ${PWD}/env -ti --rm -v /home/user/watchstate/config/user1:/config ghcr.io/arabcoders/watchstate:latest console servers:manage --add user3_plex
```

do that for each server that the user is connected to, once you finished doing that for all of your users. it's time to create a very basic bash script that you will run via cronjob if you want or or demand. 

```bash
$ touch run_jobs.sh && chmod +x run_jobs.sh
```

Then copy and repeat the following command for each user

```bash
docker run --env-file ${PWD}/env -ti --rm -v /home/user/watchstate/config/user1:/config ghcr.io/arabcoders/watchstate:latest /bin/ash -c "console state:import -v && console state:export -v"
```

once that done save the file and you can know do multi sync by running ./run_jobs.sh if you feel everything is fine, then you can add it to cronjobs.

**Comment by ArabCoders** [comment]
I'll update this issue when i have something to share regarding the multi user support.

**Comment by Splinter7914** [comment]
I see the multi user as a possible v2 option in the todo list, curious if we should expect it soon?

**Comment by arabcoders** [comment]
> I see the multi user as a possible v2 option in the todo list, curious if we should expect it soon?

Hi, it is something i would like to support, But sadly, it's still unattainable via the method we use, and the work around i came up with is just too slow

**Comment by arabcoders** [comment]
@ggogel i am happy to announce that we do now have a way to sync all users data =)

**Comment by trivarialthea** [comment]
Hi, @arabcoders, how can one enter a plex user pin for a sub-user? Adding one via the webgui (in the subusers view) results in:

> Failed to save backend settings. (400: Backend responded with 401. Most likely means token is invalid.).

**Comment by arabcoders** [comment]
> Hi, @arabcoders, how can one enter a plex user pin for a sub-user? Adding one via the webgui (in the subusers view) results in:
> 
> > Failed to save backend settings. (400: Backend responded with 401. Most likely means token is invalid.).
> 

Once you have created the users, from top switch to that user then go to backends and edit the backend go down to additional options add plex_plex_pin and fill it with the user pin.

**Comment by trivarialthea** [comment]
> Once you have created the users, from top switch to that user then go to backends and edit the backend go down to additional options add plex_plex_pin and fill it with the user pin.

Did exactly that and it gives me the error "Failed to save backend settings. (400: Backend responded with 401. Most likely means token is invalid.)."... This behaviour does not appear on the main user and I checked both the api token and the plex token on the sub user and all are valid.

**Comment by arabcoders** [comment]
> > Once you have created the users, from top switch to that user then go to backends and edit the backend go down to additional options add plex_plex_pin and fill it with the user pin.
> 
> Did exactly that and it gives me the error "Failed to save backend settings. (400: Backend responded with 401. Most likely means token is invalid.)."... This behaviour does not appear on the main user and I checked both the api token and the plex token on the sub user and all are valid.

I just checked the code, i created new home user, from the WebUI, i switched to that user, went to edit the backend, added the `PLEX_USER_PIN` option and it worked.

I have pushed a a change to the `:dev` channel to include the PIN in initial validation check, i actually  tested my own user without the PIN and it worked.

I suspect you have problem something else, i am available via discord for few hours if you are interested in chatting, you can find the link in README.md, Also if you still have the problem please open an issue so we can keep this issue completed =)

**Comment by trivarialthea** [comment]
Hey, made #649 to further discuss findings with you, that I had in discord DMs with you and to have the observations public.
