### ISSUE TITLE
Can no longer select user

### ISSUE THREAD

**Issue by kelinger** [ArabCoders/watchstate#137]
While this used to work, it seems that I can no longer choose the user during the setup process of a new connection.  This seems to happen with both Emby and Plex (haven't tried Jellyfin).  While all other parameters up to the user selection work just fine, the user prompt looks like this:

```
Select which user to associate with this server - [Default: ??]
  [0] ??
  [1] ??
```

Note that yes, I do have two users in Plex but even if I select one or the other option, the config file ends up showing that the user selected is "null" and syncing fails due to "no user selected."

WatchState 2d14a41 running in Docker on Debian 11 host.

**Comment by ArabCoders** [comment]
Hi, Thanks for the bug report, I should have fix for this in the next few mins

**Comment by ArabCoders** [comment]
@kelinger Fix is out. pull the new container and it should works as expected. sorry about this
