### ISSUE TITLE
"no backend metadata was found" - exporting "obi wan kenobi" play state to EMBY

### ISSUE THREAD

**Issue by adamb0403** [ArabCoders/watchstate#150]
The export for "obi wan kenobi" is ignored when exporting per the following error message:

`WARNING: Ignoring [Obi-Wan Kenobi (2022) - 01x004] for [emby] no backend metadata was found.`

Any idea what is causing this?

**Comment by ArabCoders** [comment]
This likely means, the import task hasn't run yet, in which case no metadata error is correct behavior as the exporter does not know yet how to contact emby about this change. Or the episode has not been matched. you tell by doing something like this `console db:list --title 'Obi-Wan Kenobi' --episode 4 --output yaml' it will tell you which servers reported the episode.

**Comment by adamb0403** [comment]
Jellyfin and plex both reported when running that command. They were both responsive the the import and exports too. Seems like an issue with the emby side of things

**Comment by ArabCoders** [comment]
could you go into your config and check which task reported the problem? was it push or export

**Comment by adamb0403** [comment]
The warning appears on both push and export log outputs

**Comment by ArabCoders** [comment]
In few minutes once #151 is built, pull the new container and the issue should be gone for now.
