### ISSUE TITLE
Have the option to select all user

### ISSUE THREAD

**Issue by ma-karai** [ArabCoders/watchstate#160]
During setup, I'd like to set up all user and not just one. Is there an option to do so?

**Comment by ArabCoders** [comment]
Hi could you please clarify what do you mean by selecting all user?

**Comment by ma-karai** [comment]
So lets say I run 2 servers, jelly and emby. I have all users on all servers. And I want to sync all watch statuses on all servers for all users.

As it is right now, i basically have to select a user for emby and sync that user to a user on jelly, If i have to do that for every user present on the server i have to repeat this process multiple times.

**Comment by ArabCoders** [comment]
Alright i understand what you mean. Unfortunately this tool is designed for single user use. However it's possible to sync multiple users using other means. Please take look at [this](https://github.com/ArabCoders/watchstate/issues/136). might help with what you need.

**Comment by ma-karai** [comment]
Yeah, i could set something up like this. Thanks for the answer

**Comment by ArabCoders** [comment]
No problem. Glad it works for you.
