### ISSUE TITLE
Jellyfin on different Base URL

### ISSUE THREAD

**Issue by joeknock90** [ArabCoders/watchstate#195]
I run my jellyfin server with the base URL of /watch, so the entire URL comes out to https://media.example.com/watch or by IP http://XXX.XXX.XXX.XXX:8096/watch. 

It doesn't seem that adding a backend URL allows for accounting for this. Maybe I'm doing something wrong?

**Comment by ArabCoders** [comment]
Hi,

Thanks for reporting the issue, indeed this is not supported at the moment. 

i am working on different task right now, I'll hopefully have fix for this in within few days. as it require non-trivial amount of code change.

**Comment by ArabCoders** [comment]
Well, i solved the problem in different way which required less code changes. as such the fix is deployed and should hit dev container build soon, but sadly GitHub is having problems right now with actions. once that is fixed I'll let you know the next steps.

**Comment by ArabCoders** [comment]
well i managed to fix the amd64 build for now, it seems arm64 still broken, anyway change the image tag to ghcr.io/arabcoders/watchstate:dev 

and try now and see if it's works for you.

**Comment by joeknock90** [comment]
Holy crap you guys are fast. I'm not currently using any arm for my container deployment so I'll test now. Thanks!

**Comment by ArabCoders** [comment]
> Just tried out the dev channel and attempting to add a jellyfin config gives this at detecting users:
> 
> ```
> 
> Trying to get users list from backend. Please wait...
> 
> [2022-07-13T12:53:25+00:00] WARNING: Unhandled exception was thrown in [JellyfinBackend: jellyfin] context. Idle timeout reached for "https://media.example.com/Users/".
> 
> Failed to get the users list from backend.
> 
> ERROR - RuntimeException: Unhandled exception was thrown in [JellyfinBackend: jellyfin] context. Idle timeout reached for "https://media.example.com/Users/"..
> 
> ```
> 
> 
> 
> I was able to type in the user manually but I'm not sure if it will pull watchstate. Still testing, just wanted to throw this up here. 

Did the url include the basePath ? i.e https://media.example.com/basePath/Users/

**Comment by joeknock90** [comment]
Hang on. I'm starting to think my container didn't actually update to the dev branch you pushed. version is reporting c025838 and it looks like that build is from 2 days ago. 

Might just have to wait a bit for github? Gonna try pulling again. Sorry about that!

**Comment by joeknock90** [comment]
Hey so I'm an idiot. I didn't up the container after pulling. I haven't had all of my coffee yet this morning. 

With the new build I'm getting this in the logs and the container continues to restart. 

`media-servers-watchstate-1  | exec /usr/bin/entrypoint-docker: exec format error`

**Comment by ArabCoders** [comment]
hmm it seems this error indicate that you are running unsupported build on platform, i suspect it has something with the fix we deployed yesterday for builds. new build should be up soon. i'll let you know.

**Comment by joeknock90** [comment]
Completely working now! Thanks!

**Comment by ArabCoders** [comment]
Glad it's working for you now =) do not hesitate to report any problem that you face.
