### ISSUE TITLE
Two issues on inital docker deployment.

### ISSUE THREAD

**Issue by arcoast** [ArabCoders/watchstate#206]
Trying to run the `docker-compose.yml` as published causes an error and container not starting.

```yaml
    watchstate:
        image: ghcr.io/arabcoders/watchstate:latest
        container_name: watchstate
        restart: unless-stopped
        environment:
            - WS_UID=99
            - WS_GID=100
        ports:
            - 8081:80
        volumes:
            - ${CONFIG}/watchstate:/config
```

Gives rise to:

```bash
root@server:~# docker logs watchstate
groupmod: GID '100' already exists
groupmod: GID '100' already exists
groupmod: GID '100' already exists
groupmod: GID '100' already exists
groupmod: GID '100' already exists
```

Now, if I change the `WS_UID` & `WS_GID` both to `1000` then the container gets a bit further but also gives rise to an error:

```yaml
    watchstate:
        image: ghcr.io/arabcoders/watchstate:latest
        container_name: watchstate
        restart: unless-stopped
        environment:
            - WS_UID=1000
            - WS_GID=1000
        ports:
            - 8081:80
        volumes:
            - ${CONFIG}/watchstate:/config
```

```bash
root@server:~# docker logs watchstate
[2022-07-17T21:38:42+0000] Starting HTTP Server.
[2022-07-17T21:38:42+0000] Starting Task Scheduler.
[2022-07-17T21:38:42+0000] Starting Cache Server.

*** FATAL CONFIG FILE ERROR (Redis 7.0.2) ***
Reading the configuration file, at line 12
>>> 'dir /config/cache/'
No such file or directory
[2022-07-17T21:38:44+0000] Starting HTTP Server.
[2022-07-17T21:38:44+0000] Starting Task Scheduler.
[2022-07-17T21:38:44+0000] Starting Cache Server.
```

Manually creating `/config/cache` resolves this error and enables the container to start.

```bash
root@server:~# docker logs watchstate
[2022-07-17T21:54:25+0000] Starting HTTP Server.
[2022-07-17T21:54:25+0000] Starting Task Scheduler.
[2022-07-17T21:54:26+0000] Starting Cache Server.
[2022-07-17T21:54:26+0000] Caching tool Routes.
[2022-07-17T21:54:26+0000] Running database migrations.
[2022-07-17T21:54:26+0000] Running database maintenance tasks.
[2022-07-17T21:54:26+0000] Ensuring State table has correct indexes.
[2022-07-17T21:54:26+0000] Running - WatchState 6c38815
[17-Jul-2022 21:54:26] NOTICE: fpm is running, pid 1
[17-Jul-2022 21:54:26] NOTICE: ready to handle connections
```

So in summary I think there are two issues:

1.  The `WS_UID` and `WS_GID` variables don't seem to work if the variable is set from the default `1000:1000`
2.  In a fresh docker deployment, the `/config/cache` directory isn't created giving rise to an error message.

**Comment by ArabCoders** [comment]
Thank you for reports. 

I will take look and hopefully will deploy fix in the next build. My testing environment have a prebuilt config structure which is probably why i did not notice the bug as it was introduced recently when i made changes to the docker entry point. 

For the gid/uid i have no idea why it's behaving this way. i will have to do some reading on that. 

So Thank you for noticing the bugs.

**Comment by arcoast** [comment]
Thanks for the hard work.  Let me know if you want me to do any testing my end.  Happy to help any way I can.

**Comment by arcoast** [comment]
Regarding the groupmod error, I'm running this on Unraid which uses `99:100` as default user:group.  The groupmod error is occuring as the 100 group already exists in the container environment.

```bash
root@server:~# docker exec -it watchstate sh
/config # grep 100 /etc/group
www-data:x:1000:www-data,nginx
users:x:100:games
/config # 
```

**Comment by ArabCoders** [comment]
@arcoast i pushed a fix for both of the issues, please do try now and report back
