### ISSUE TITLE
Function On Demand explained somewhere ?

### ISSUE THREAD

**Issue by alturismo** [ArabCoders/watchstate#240]
Hi again,

may a question how to interpret the function ondemand ?

i looked at the Readme, FAQ's but couldnt find anything about this to sync (besides cron & webhook), just as an Alternative ... ?

may i didnt understand it or just cant find it ;)

**Comment by ArabCoders** [comment]
Hi,

On demand, means running the import and export command manually instead of on schedule or via webhook triggers.

**Comment by alturismo** [comment]
thanks ;) my fault ;)

**Comment by ArabCoders** [comment]
> thanks ;) my fault ;)

No worries feel free to ask anything i need to improve the docs =)
