### ISSUE TITLE
webhooks explained user setup

### ISSUE THREAD

**Issue by alturismo** [ArabCoders/watchstate#242]
while i was settings up my plex and emby server, it asked fine which user to take and i also said yes and continued ...

no issue here as im running both backends more or less single user ... but

in the end, i have to disable the user function completely so webhooks do work

![image](https://user-images.githubusercontent.com/8406490/188682078-331a657d-1383-463f-a0ca-a198c8a26752.png)

otherwise i always end up in

`... webhook.ERROR: token is valid, User matching failed. {"...`

while the setup showed me the proper user (me, alturismo) ... is this the expected behaviour ?

and as general question, should it also sync the playstate, watchstate, not only watched, unwatched, ... also timestamp, as sample what i mean, plex is standing on this episode here

![image](https://user-images.githubusercontent.com/8406490/188682878-c6fe80a8-32b4-4fb0-ab38-7b5c95112e7a.png)

while emby aint updated to continue on the same spot, would start from beginning then

![image](https://user-images.githubusercontent.com/8406490/188683088-5723d9e9-3a64-4f14-993d-f5974d08ebbf.png)

i hope you understand what i mean ;)

**Comment by ArabCoders** [comment]
Hi,



> otherwise i always end up in
> 
> `... webhook.ERROR: token is valid, User matching failed. {"...`

Hi, the error depends on what kind of event was sent, some events do not include userdata as such it will fail the check, for emby to check if the user is correct play something and watch the log it should report queued items correctly. Generally for emby/jellyfin you should select your user there and disable watchstate user match however as the platform support it unlike plex which does not support user matching which this feature is intended for.


> and as general question, should it also sync the playstate, watchstate, not only watched, unwatched, ... also timestamp, as sample what i mean, plex is standing on this episode here

The webhook only sync played/unplayed events. For in progress items there are some plans hopefully for next major version to include them as planned in #130

**Comment by alturismo** [comment]
> for emby to check if the user is correct play something and watch the log it should report queued items correctly.

i was pretty sure i checked it like this (as this is also in the readme) but i have to admit, yes, while enabled it works for emby



> For in progress items there are some plans hopefully for next major version to include them as planned in #130

i should ve readed this ahead ;) looking forward for it

thanks for this nice app
