### ISSUE TITLE
Error from Jellyfin causes watchstate to skip

### ISSUE THREAD

**Issue by matthewpritchett** [ArabCoders/watchstate#245]
First, awesome application. I was using this to migrate from the linuxserver.io Jellyfin docker container to the official one. Anyway, importing always worked super fast and accurate. Exporting would end up receiving slow responses from Jellyfin about 500-1000 item in causing watchstate to error out but still complete. So, I basically had to force export repeatedly since the watchstates state would  get messed up and report that nothing needed exported. I eventually got it to export everything by repeatedly doing the force export but still have a few watched statuses that never made it. Overall, worked for what I needed but maybe a throttle option for export or ability to wait longer for a response from the server?

Thanks!

**Comment by ArabCoders** [comment]
Hi, It's nice to see it's working, do you happen to have some logs to help further see where the problem from? using something like

```bash
docker exec -ti watchstate console system:logs
```

the tool is configured to wait `5min` per segmented request and then the timeout killer will kick in, it's possible to increase the timeout further using [configuration option](https://github.com/ArabCoders/watchstate/blob/master/FAQ.md#q-sync-operations-are-failing-due-to-request-timeout), and for Jellyfin/Emby you could also use the environment variable `WS_LIBRARY_SEGMENT` with large number to reduce the amount of requests as well, the segmentation had to be done to combat future plex `400 bad request` from larger requests.

if you can give me logs i can give better specific tips

**Comment by matthewpritchett** [comment]
Awesome, I didn’t know about WS_LIBRARY_SEGMENT. I’ll check that out and try to re-run the force export to see if I can get it to do it again. Unfortunately or fortunately, I had gotten everything migrated so I shut the old one down and the new one has the updated watch states. But I’ll check and let you know. Thanks again for an awesome tool.

**Comment by ArabCoders** [comment]
Logs are still saved in `/config/logs/`  if you didn't delete the data folder you will find them there, `app.{date}.log`, anyway glad it's working for you now.

waiting on your results.

**Comment by matthewpritchett** [comment]
Found the log file from yesterday. It's 19MB and has a lot of names of my media. Any particular place you want me to send it to? Could probably email it to you if possible.

**Comment by ArabCoders** [comment]
> Found the log file from yesterday. It's 19MB and has a lot of names of my media. Any particular place you want me to send it to? Could probably email it to you if possible.

Just few lines with ERROR in them, with some logs around them to understand the context.

**Comment by matthewpritchett** [comment]
[2022-09-17T11:58:39.999736-05:00] logger.ERROR: Unhandled exception thrown during request to change play state of [jellyfin2] Episode [_removedforprivacy_]. {"library":{"id":"a656b907eb3a73532e40e44b968d0225","title":"Shows","type":"tvshows","totalRecords":20699,"url":"http://_removedforprivacy_:8097/Users/_removedforprivacy_/items/?sortBy=DateCreated&sortOrder=Ascending&parentId=_removedforprivacy_&recursive=true&enableUserData=true&enableImages=false&excludeLocationTypes=Virtual&fields=ProviderIds%2CDateCreated%2COriginalTitle%2CSeasonUserData%2CDateLastSaved%2CPremiereDate%2CProductionYear%2CPath&includeItemTypes=Movie%2CEpisode&limit=1000&startIndex=13000"},"segment":{"number":14,"of":21.0,"size":1000},"item":{"id":"2ff84d9c1b86c0dc7ec437a2c0930d65","url":{"App\\Libs\\Uri":"http://_removedforprivacy_:8097/Users/_removedforprivacy_/PlayedItems/_removedforprivacy_"}},"play_state":"Played","exception":{"file":"/opt/app/vendor/symfony/http-client/Chunk/ErrorChunk.php","line":62,"kind":"Symfony\\Component\\HttpClient\\Exception\\TimeoutException","message":"Idle timeout reached for \"http://_removedforprivacy_:8097/Users/_removedforprivacy_/PlayedItems/_removedforprivacy_\"."}} []

Pretty much all of them look like above. I put _removedforprivacy_ for replacing my user id and server info but hopefully the overall error is there. Let me know if not. All the logs in Jellyfin was just saying it had slow responses for the play state requests. So, I'm guessing watchstate was erroring and just continuing on.

**Comment by ArabCoders** [comment]
> ```log
> [2022-09-17T11:58:39.999736-05:00] logger.ERROR: Unhandled exception thrown during request to change play state of [jellyfin2] Episode [_removedforprivacy_]. {"library":{"id":"a656b907eb3a73532e40e44b968d0225","title":"Shows","type":"tvshows","totalRecords":20699,"url":"http://_removedforprivacy_:8097/Users/_removedforprivacy_/items/?sortBy=DateCreated&sortOrder=Ascending&parentId=_removedforprivacy_&recursive=true&enableUserData=true&enableImages=false&excludeLocationTypes=Virtual&fields=ProviderIds%2CDateCreated%2COriginalTitle%2CSeasonUserData%2CDateLastSaved%2CPremiereDate%2CProductionYear%2CPath&includeItemTypes=Movie%2CEpisode&limit=1000&startIndex=13000"},"segment":{"number":14,"of":21.0,"size":1000},"item":{"id":"2ff84d9c1b86c0dc7ec437a2c0930d65","url":{"App\\Libs\\Uri":"http://_removedforprivacy_:8097/Users/_removedforprivacy_/PlayedItems/_removedforprivacy_"}},"play_state":"Played","exception":{"file":"/opt/app/vendor/symfony/http-client/Chunk/ErrorChunk.php","line":62,"kind":"Symfony\\Component\\HttpClient\\Exception\\TimeoutException","message":"Idle timeout reached for \"http://_removedforprivacy_:8097/Users/_removedforprivacy_/PlayedItems/_removedforprivacy_\"."}} []
> 
> ```
> 
> 
> Pretty much all of them look like above. I put _removedforprivacy_ for replacing my user id and server info but hopefully the overall error is there. Let me know if not. All the logs in Jellyfin was just saying it had slow responses for the play state requests. So, I'm guessing watchstate was erroring and just continuing on.


Indeed its as you described, `Idle timeout reached` 

This error means the timeout handler was invoked and killed the request, which means one of this possible scenarios
* The connection between the tool and the jellyfin is quite slow `network related`
* jellyfin is not able to reply fast enough `5min` to request due to probably `fragmented database` or probably slow disk.

**Comment by matthewpritchett** [comment]
That’s basically what I assumed had happened. Tool did work when I kept just forcing the export as it would slowly make its way through them a bit more each time lol. Thanks again!

**Comment by ArabCoders** [comment]
Np glad it works for you.
