### ISSUE TITLE
Two Way Syncing?

### ISSUE THREAD

**Issue by DANW999** [ArabCoders/watchstate#248]
Hi there, thank you for this project. I am interested in using this as an alternative to Plex's third party sync. Could you confirm that this syncs two ways? What I mean by that, is if I have two Plex servers and I watch a movie on one Plex server and then watch different movie on another Plex server, once I sync will both Plex servers now show that both movies have been watched? Thank you.

**Comment by ArabCoders** [comment]
Hello

Yes thats the idea.
