### ISSUE TITLE
Can't sync to Plex?

### ISSUE THREAD

**Issue by Skyfay** [ArabCoders/watchstate#254]
Hey, First of all thank you for this nice project!

I have an Emby server and am now switching to Plex. I would like to take over the current "seen/unseen" data for my users. I was able to successfully import the data from Emby, but failing to export to Plex.

```
root@Server /docker/media-server # docker exec -ti watchstate console state:export -v --select-backends 'plex'
[2022-10-27T18:01:34+00:00] NOTICE: DATABASE: Loading changed items since [2022-10-27 18:01:34 UTC].
[2022-10-27T18:01:34+00:00] NOTICE: SYSTEM: Using push mode for [0] backends and export mode for [1] backends.
[2022-10-27T18:01:34+00:00] NOTICE: Export mode start.
[2022-10-27T18:01:34+00:00] NOTICE: SYSTEM: Preloading DirectMapper data.
[2022-10-27T18:01:34+00:00] NOTICE: SYSTEM: Preloading DirectMapper data is complete.
[2022-10-27T18:01:34+00:00] NOTICE: SYSTEM: Exporting play state to [plex].
[2022-10-27T18:01:35+00:00] ERROR: Request for [plex] libraries returned with unexpected [401] status code.
[2022-10-27T18:01:35+00:00] WARNING: SYSTEM: Not updating last export date. [plex] report an error.
[2022-10-27T18:01:35+00:00] NOTICE: SYSTEM: Sending [0] play state comparison requests.
[2022-10-27T18:01:35+00:00] NOTICE: SYSTEM: Sent [0] play state comparison requests.
[2022-10-27T18:01:35+00:00] NOTICE: Export mode ends.
[2022-10-27T18:01:35+00:00] NOTICE: SYSTEM: No play state changes detected.
[2022-10-27T18:01:35+00:00] WARNING: SYSTEM: Not updating last export date for [plex]. Backend reported an error.
```
I can't find my error, maybe I can get some help here?

**Comment by ArabCoders** [comment]
Hi,

> [2022-10-27T18:01:35+00:00] ERROR: Request for [plex] libraries returned with unexpected [401] status code.

indicates invalid plex token, please check it when you add plex server with correct token it should pick the server identifier automatically if it doesn't this mean it's unable to contact the server you can also run the same command with the following flags `-vvv --trace --context`

**Comment by Skyfay** [comment]
> 
I have a Plex Administrator account and a test user. And I would now like to take the test user for the export. If I take the token from a medium via the XML file, I can only select my administrator account. I read the token from my test account using the web browser developer tools. Is that wrong?

**Comment by ArabCoders** [comment]
the 401 error indicates an unauthorized access, which likely means the token has no access to the requested server or resources, if you want to use non admin token you have to added first, then run

```
docker exec -ti watchstate console backend:users:list server_name --with-tokens
```

take the token associated with the user and replace the admin one this should do the trick

**Comment by Skyfay** [comment]
> 
The problem is when I take the server token it only shows me my administrator account and not the test account.

**Comment by ArabCoders** [comment]
Hmm, when i go to plex home and create managed user, and log into that user at least one, it does show up in plex api, could you try doing that?

**Comment by Skyfay** [comment]
I'm sorry Maybe they misunderstood me. The test account is a completely different Plex account and not a home user that was created. I released the Plex test account as a "friend" and the media.

**Comment by ArabCoders** [comment]
> I'm sorry Maybe they misunderstood me. The test account is a completely different Plex account and not a home user that was created. I released the Plex test account as a "friend" and the media.

Ok i understand now, i haven't really tested recruit friend and how they interact with the api, im working right now on new plex command to show you list of the servers associated with a token, it should hopefully fix it

i'll let you know once i have it in dev channel

**Comment by Skyfay** [comment]
Oh, that's super nice. Thanks

**Comment by ArabCoders** [comment]
> Oh, that's super nice. Thanks

Ok, the new command is up in the dev channel, could you switch your container tag to `ghcr.io/arabcoders/watchstate:dev` pull the new container and then run the following command

```
docker exec -ti watchstate console plex:discover [plex_token]
```

it should show you list of servers associated with the given token you are mainly intersted in the `Uri` and `name`

**Comment by Skyfay** [comment]
Uhm...
```
watchstate       | [2022-10-27T21:04:20+0200] INFO: No environment file present at [/config/config/.env].
watchstate       | [2022-10-27T21:04:20+0200] INFO: No environment file present at [/config/config/.env].
watchstate       | [2022-10-27T21:04:21+0200] INFO: No environment file present at [/config/config/.env].
watchstate       | [2022-10-27T21:04:22+0200] INFO: No environment file present at [/config/config/.env].
watchstate       | [2022-10-27T21:04:23+0200] INFO: No environment file present at [/config/config/.env].
watchstate       | [2022-10-27T21:04:25+0200] INFO: No environment file present at [/config/config/.env].
watchstate       | [2022-10-27T21:04:28+0200] INFO: No environment file present at [/config/config/.env].
watchstate       | [2022-10-27T21:04:35+0200] INFO: No environment file present at [/config/config/.env].
watchstate       | [2022-10-27T21:04:48+0200] INFO: No environment file present at [/config/config/.env].
watchstate       | [2022-10-27T21:05:14+0200] INFO: No environment file present at [/config/config/.env].
watchstate       | [2022-10-27T21:05:21+0200] INFO: No environment file present at [/config/config/.env].
watchstate       | [2022-10-27T21:05:21+0200] INFO: No environment file present at [/config/config/.env].
watchstate       | [2022-10-27T21:05:22+0200] INFO: No environment file present at [/config/config/.env].
watchstate       | [2022-10-27T21:05:23+0200] INFO: No environment file present at [/config/config/.env].
watchstate       | [2022-10-27T21:05:24+0200] INFO: No environment file present at [/config/config/.env].
```

**Comment by ArabCoders** [comment]
is the container crashing and going into restart loop?

**Comment by Skyfay** [comment]
Yes

**Comment by ArabCoders** [comment]
If you run this does it crash as well?

```
docker run --rm -ti --name test_ws ghcr.io/arabcoders/watchstate:dev
```

**Comment by Skyfay** [comment]
Yes

**Comment by ArabCoders** [comment]
Alright, could you please copy the entire output i need to see the complete error this INFO should not really crash the container as it's just FYI message. make sure to 

```
docker pull ghcr.io/arabcoders/watchstate:dev
```

i just run the container myself right now and i got this

```
$ docker run --rm -ti --name baz ghcr.io/arabcoders/watchstate:dev
[2022-10-27T19:10:44+0000] INFO: No environment file present at [/config/config/.env].
[2022-10-27T19:10:44+0000] Starting Cache Server.
[2022-10-27T19:10:44+0000] Starting HTTP Server.
2022/10/27 19:10:44.990 INFO    using provided configuration    {"config_file": "/opt/config/Caddyfile", "config_adapter": ""}
2022/10/27 19:10:44.991 INFO    admin   admin endpoint started  {"address": "tcp/localhost:2019", "enforce_origin": false, "origins": ["//localhost:2019", "//[::1]:2019", "//127.0.0.1:2019"]}
2022/10/27 19:10:44.991 WARN    http    server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server {"server_name": "srv0", "http_port": 8080}
2022/10/27 19:10:44.991 INFO    tls.cache.maintenance   started background certificate maintenance      {"cache": "0xc0001519d0"}
2022/10/27 19:10:44.991 INFO    tls     cleaning storage unit   {"description": "FileStorage:/config/.local/share/caddy"}
2022/10/27 19:10:44.991 INFO    tls     finished cleaning storage units
2022/10/27 19:10:44.991 INFO    autosaved config (load with --resume flag)      {"file": "/config/.config/caddy/autosave.json"}
2022/10/27 19:10:44.991 INFO    serving initial configuration
Successfully started Caddy (pid=33) - Caddy is running in the background
[2022-10-27T19:10:44+0000] Starting Task Scheduler.
[2022-10-27T19:10:44+0000] Caching tool Routes.
[2022-10-27T19:10:45+0000] Running database migrations.
[2022-10-27T19:10:45+0000] Running database maintenance tasks.
[2022-10-27T19:10:45+0000] Ensuring State table has correct indexes.
[2022-10-27T19:10:45+0000] Running - WatchState 71a9a53
[27-Oct-2022 19:10:45] NOTICE: fpm is running, pid 1
[27-Oct-2022 19:10:45] NOTICE: ready to handle connections
```

which is the expected output

**Comment by Skyfay** [comment]
```Status: Image is up to date for ghcr.io/arabcoders/watchstate:dev```
I just got this output:
```
root@Server /docker/media-server # docker run --rm -ti --name baz ghcr.io/arabcoders/watchstate:dev
[2022-10-27T19:12:57+0000] INFO: No environment file present at [/config/config/.env].
root@SkyServer /docker/media-server #
```

**Comment by ArabCoders** [comment]
do you have discord or matrix id? so we can diagnose it quicker

**Comment by Skyfay** [comment]
Skyfay#1907

**Comment by ArabCoders** [comment]
the problem with the dev tag seems to be cache related on the user system, as we tested different scenarios and only one server has this problem. if later it's camas up please re-post the issue
