### ISSUE TITLE
[BUG] Scheduled sync doesn't work, but manual does

### ISSUE THREAD

**Issue by mhbates** [ArabCoders/watchstate#285]
**Describe the bug**
The scheduled cron import & export doesn't seem to work. I checked the task status and it shows them as scheduled, but watch state doesn't actually sync. Running the import/export manually works. Any ideas?

**Comment by ArabCoders** [comment]
@mhbates any updates?

**Comment by mhbates** [comment]
Thank you for the quick help. The commands return expected results - import and export crons enabled, NextRuns scheduled as they should be, and the log showing recent activity. It seems to be working now. Previously, the first two steps looked fine but it wasn't actually syncing. If it happens again, I'll try looking at the recent log activity and see if that tells me anything.

**Comment by ArabCoders** [comment]
Glad it's working for you.

**Comment by coolguymatt** [comment]
I have this same issue. Is there something I can do to troubleshoot this? When I try the third command, I get this:

Log file [config/logs/task.20230203.log] does not exist or is empty. This means it has been pruned, the date is incorrect or nothing has written to that file yet.

**Comment by ArabCoders** [comment]
> I have this same issue. Is there something I can do to troubleshoot this? When I try the third command, I get this:
> 
> Log file [config/logs/task.20230203.log] does not exist or is empty. This means it has been pruned, the date is incorrect or nothing has written to that file yet.

Please open new issue regarding this or jump into discord. There is a new command `console system:report` which should tell you if you actually enabled the tasks or not now =)
