### ISSUE TITLE
Watchstate Tasks (logging) not honoring WS_TZ setting [BUG]

### ISSUE THREAD

**Issue by ahughes03** [ArabCoders/watchstate#293]
**Describe the bug**
 

I've set my `WS_TZ` environmental variable to `America/Los_Angeles`. Tasks note the correct local time when I view them, but new logs are created based on UTC. As an example, I'm submitting this at/around 8:00pm on 12/20 local time, and my instance of watchstate has is already writing to the `task.20221221.log` file, which shouldn't be created for another 4ish hours. That file shows "correct" timestamps when I cat or tail the file.

Further, the `docker exec -ti watchstate console system:logs --type task --follow` command will tail the locally correct log, which is not necessarily the one being written to. Ex: if I run the command at 8:00pm local time on 12/20/22, it tails/cats the `task.20221220.log` file, which hasn't been written to since 3:58pm PST (since watchstate started writing to the `task.20221221.log` file at 4:00PM PST.

**Expected behavior**
 

I expect watchstate to continue writing to the log file based on the WS_TZ variable, and create the next set of log files at midnight of that timezone.

**Comment by ArabCoders** [comment]
Thanks for the report, 

Indeed that's the case as the logfile is created before environment variables being created. I'll try to find work around for it
