### ISSUE TITLE
[BUG] Unable to run state:import for Jellyfin

### ISSUE THREAD

**Issue by ieaves** [ArabCoders/watchstate#302]
**Describe the bug**

Running `console state:import -v` errors with `ERROR: Request for [jellyfin] libraries returned with unexpected [400] status code.`

**To Reproduce**

I followed the readme guide to add a Jellyfin backend. The backend was added successfully without any reported errors. It accepted the provided API key and successfully queried a list of users during the question sequence of the `console config:add jellyfin` flow. 

Upon running the `console state:import -v` command I reliably receive a 400 error even after deleting and re-adding the backend.

**Expected behavior**

The jellyfin backend imports watchstate.

**Screenshots**

<img width="948" alt="Screenshot 2023-01-12 at 11 18 04 PM" src="https://user-images.githubusercontent.com/7785207/212243198-50918018-556c-435c-9633-34ab88e54dc4.png">

**Basic report**

# Please use the following command to generate basic report to help us diagnose the issue
# Make sure review the logs sections as it might have some private information.

docker exec -ti watchstate console system:report

Please put the output in a code block like this

```
[ Basic Report ]

WatchState Version: 24a1270
Timezone: 
Running in Container? Yes
Data Path: /config
Temp Path: /config
Database Migrated?: Yes
Has .env file? No
Report Generated At: 2023-01-13T05:19:16+00:00

[ Backends ]

[ Plex ==> plex ]

Is backend URL HTTPS? Yes
Has Unique Identifier? Yes
Has User? Yes
Export Enabled? Yes
Time since last export? 2023-01-13T05:18:44+00:00
Play state import enabled? Yes
Metadata only import enabled? No
Time since last import? 2023-01-13T05:18:32+00:00
Has webhook token? Yes
Is webhook match user id enabled? Yes
Is webhook match backend unique id enabled? Yes
Has custom options? No
{}
[ Jellyfin ==> jellyfin_home ]

Is backend URL HTTPS? Yes
Has Unique Identifier? Yes
Has User? Yes
Export Enabled? Yes
Time since last export? Never
Play state import enabled? Yes
Metadata only import enabled? Yes
Time since last import? Never
Has webhook token? Yes
Is webhook match user id enabled? No
Is webhook match backend unique id enabled? No
Has custom options? Yes
{"IMPORT_METADATA_ONLY":true}
[ Tasks ]

[ Import ]

Is Task enabled? Yes
Which flags are used to run the task? -v
When the task scheduled to run at? */1 * * * *
When is the next scheduled run? 2023-01-13T05:20:00+00:00

[ Export ]

Is Task enabled? Yes
Which flags are used to run the task? -v
When the task scheduled to run at? */1 * * * *
When is the next scheduled run? 2023-01-13T05:20:00+00:00

[ Push ]

Is Task enabled? No

[ Backup ]

Is Task enabled? No

[ Prune ]

Is Task enabled? Yes
Which flags are used to run the task? -v
When the task scheduled to run at? 0 */12 * * *
When is the next scheduled run? 2023-01-13T06:00:00+00:00

[ Indexes ]

Is Task enabled? Yes
Which flags are used to run the task? -v
When the task scheduled to run at? 0 3 * * 3
When is the next scheduled run? 2023-01-18T09:00:00+00:00

[ Requests ]

Is Task enabled? Yes
Which flags are used to run the task? -v --no-stats
When the task scheduled to run at? */2 * * * *
When is the next scheduled run? 2023-01-13T05:20:00+00:00

[ Logs ]

[ /config/logs/app.20230112.log ]

[2023-01-12T23:13:40.764273-06:00] logger.ERROR: Request for [jellyfin_home] libraries returned with unexpected [400] status code. [] []
[2023-01-12T23:13:50.135645-06:00] logger.ERROR: Request for [jellyfin_home] libraries returned with unexpected [400] status code. [] []
[2023-01-12T23:14:52.484707-06:00] logger.ERROR: Request for [jellyfin_home] libraries returned with unexpected [400] status code. [] []
[2023-01-12T23:15:01.341186-06:00] logger.ERROR: Request for [jellyfin_home] libraries returned with unexpected [400] status code. [] []
[2023-01-12T23:16:05.168714-06:00] logger.ERROR: Request for [jellyfin_home] libraries returned with unexpected [400] status code. [] []
[2023-01-12T23:16:15.714040-06:00] logger.ERROR: Request for [jellyfin_home] libraries returned with unexpected [400] status code. [] []
[2023-01-12T23:17:18.614872-06:00] logger.ERROR: Request for [jellyfin_home] libraries returned with unexpected [400] status code. [] []
[2023-01-12T23:17:29.740789-06:00] logger.ERROR: Request for [jellyfin_home] libraries returned with unexpected [400] status code. [] []
[2023-01-12T23:18:32.784215-06:00] logger.ERROR: Request for [jellyfin_home] libraries returned with unexpected [400] status code. [] []
[2023-01-12T23:18:44.182417-06:00] logger.ERROR: Request for [jellyfin_home] libraries returned with unexpected [400] status code. [] []

[ /config/logs/access.20230112.log ]

access log file is empty or does not exists.

[ /config/logs/task.20230112.log ]

[2023-01-12T23:18:43-06:00] NOTICE: SYSTEM: Preloading DirectMapper data is complete.
[2023-01-12T23:18:43-06:00] NOTICE: SYSTEM: Exporting play state to [jellyfin_home].
[2023-01-12T23:18:44-06:00] ERROR: Request for [jellyfin_home] libraries returned with unexpected [400] status code.
[2023-01-12T23:18:44-06:00] WARNING: SYSTEM: Not updating last export date. [jellyfin_home] report an error.
[2023-01-12T23:18:44-06:00] NOTICE: SYSTEM: Sending [0] play state comparison requests.
[2023-01-12T23:18:44-06:00] NOTICE: SYSTEM: Sent [0] play state comparison requests.
[2023-01-12T23:18:44-06:00] NOTICE: Export mode ends.
[2023-01-12T23:18:44-06:00] NOTICE: SYSTEM: No play state changes detected.
[2023-01-12T23:18:44-06:00] WARNING: SYSTEM: Not updating last export date for [jellyfin_home]. Backend reported an error.

[ /config/logs/app.20230111.log ]

app log file is empty or does not exists.

[ /config/logs/access.20230111.log ]

access log file is empty or does not exists.

[ /config/logs/task.20230111.log ]

task log file is empty or does not exists.
```

**Additional context**

I'm a new user, it's perfectly possible I've done something wrong here but I followed the instructions available in the Readme and was able to successfully connect to plex.

Both watchstate, jellyfin, and plex are deployed on Kubernetes and the issue is reproducible regardless of the networking configuration provided to watchstate for jellyfin (i.e. it fails whether accessed through `https://jellyfin.domainname.com` or using K8's internal DNS resolver.

The currently deployed version of Jellyfin is an up to date but otherwise standard instance of the `lscr.io/linuxserver/jellyfin:latest` container image.

**Comment by ArabCoders** [comment]
Hi,

Thank you for your report, could you do the following please.

```
docker exec -ti state:import -s jellyfin_home -vvv --context --trace
```

it should provide more information on the failure, so we can take it further =)

**Comment by ieaves** [comment]
Hey @ArabCoders thanks for taking a look. I'm going to close the issue because it looks like an issue with my Jellyfin instance. After tearing it down and rebuilding from scratch I was able to get things up and running as expected :).

**Comment by ArabCoders** [comment]
Thanks for the update. Glad everything is working for you. feel free to ask if you face any problems.

**Comment by LLDaLastDon** [comment]
I know this is closed but I'm still getting this error after starting from scratch.  I did notice that when I added jellyfin as a backend it did not find a unique identifier.

**Comment by ArabCoders** [comment]
> @ArabCoders I know this is closed but I'm still getting this error after starting from scratch. I did notice that when I added jellyfin as a backend it did not find a unique identifier.

If you didn't get a unique identifier this most likely means the API token is wrong or the URL isn't working

go inside container i.e

```bash
docker exec -ti watchstate bash
```

and run the following command

```bash
curl -v '<jellyfin_host>/system/Info' -H 'X-MediaBrowser-Token: <api_token>'
```

replace `<jellyfin_host>` with your jellyfin URL i.e. `http://jf.example.com` and `<api_token>` with your token. and post the result pls

**Comment by LLDaLastDon** [comment]
It pulls the users correctly using the API.  This is why I'm so confused.  The output is below.  I removed the actually domain for security reasons.

[2023-09-29T04:00:02+0000] INFO: No environment file present at [/config/config/.env].
[2023-09-29T04:00:02+0000] Caching tool Routes.
[2023-09-29T04:00:02+0000] Running database migrations.
[2023-09-29T04:00:02+0000] Running database maintenance tasks.
[2023-09-29T04:00:02+0000] Ensuring State table has correct indexes.
[2023-09-29T04:00:02+0000] Running - WatchState 20230915-063bdf4
* processing: https://jellyfin.domain.com
*   Trying 10.0.20.20:443...
* Connected to jellyfin.domain.com (10.0.20.20) port 443
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=*.domain.com
*  start date: Sep 25 20:56:01 2023 GMT
*  expire date: Dec 24 20:56:00 2023 GMT
*  subjectAltName: host "jellyfin.domain.com" matched cert's "*.domain.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* using HTTP/2
* h2 [:method: GET]
* h2 [:scheme: https]
* h2 [:authority: jellyfin.domain.com]
* h2 [:path: /]
* h2 [user-agent: curl/8.2.1]
* h2 [accept: */*]
* h2 [x-mediabrowser-token: c8410a306d074bc58803d7781325b38e]
* Using Stream ID: 1
> GET / HTTP/2
> Host: jellyfin.domain.com
> User-Agent: curl/8.2.1
> Accept: */*
> X-MediaBrowser-Token: c8410a306d074bc58803d7781325b38e
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 302
< server: openresty
< date: Fri, 29 Sep 2023 04:00:02 GMT
< content-length: 0
< location: web/
< strict-transport-security: max-age=63072000; preload
< x-served-by: jellyfin.domain.com
<
* Connection #0 to host jellyfin.domain.com left intact

**Comment by ArabCoders** [comment]
Could you try re-run the add command with the `-vvv --context --trace` flags and see the output? it might give you clue otherwise hope later on discord

**Comment by LLDaLastDon** [comment]
looks like something is going on when its trying to access the system/Info URL.  The verbose output has `unique identifier returned with unexpected [403] status code` and the response from the system/Info URL is blank.

**Comment by ArabCoders** [comment]
403 indicates invalid token for some reason but if you are able to list the users i am not sure how that is possible. hop on discord so we can discuss this further
