### ISSUE TITLE
[BUG] Emby backend:library:unmatched returning movie folders even though the movies are matched

### ISSUE THREAD

**Issue by aptalca** [ArabCoders/watchstate#319]
**Describe the bug**
When I run `docker exec -ti watchstate console backend:library:unmatched emby`, it returns every single movie folder I have in my library, even thought the movies are matched and the import/export is behaving without issues.

**To Reproduce**
Have each movie in its own folder
Add them to emby library
Import into watchstate
Run `backend:library:unmatched`

The results include every single movie folder listed with the `Type` listed as `Folder` and `Title` listed as the folder name
```
│ Id      │ Type   │ Library │ Title                            │ Year │
├─────────┼────────┼─────────┼──────────────────────────────────┼──────┤
│ 64613   │ Folder │ Movies  │ '71 (2014) 720p                  │      │
├─────────┼────────┼─────────┼──────────────────────────────────┼──────┤
│ 63770   │ Folder │ Movies  │ [REC].2.2009.REPACK.720p.BluRa.. │      │
├─────────┼────────┼─────────┼──────────────────────────────────┼──────┤
│ 310909  │ Folder │ Movies  │ 1+1 (2018)                       │      │
```

**Expected behavior**
Movie folders should not be listed as unmatched if the movie is matched

**Screenshots**
```
# docker exec -ti watchstate console backend:search:query emby zootopia
┌───────┬───────┬──────────┬──────┬─────────────────────────┬───────────┐
│ Id    │ Type  │ Title    │ Year │ AddedAt                 │ WatchedAt │
├───────┼───────┼──────────┼──────┼─────────────────────────┼───────────┤
│ 66107 │ Movie │ Zootopia │ 2016 │ 2016-05-19 17:51:56 EDT │ Never     │
└───────┴───────┴──────────┴──────┴─────────────────────────┴───────────┘
```
```
# docker exec -ti watchstate console backend:search:id emby 63871
┌───────┬────────┬──────────────────────┬──────┬─────────────────────────┐
│ Id    │ Type   │ Title                │ Year │ AddedAt                 │
├───────┼────────┼──────────────────────┼──────┼─────────────────────────┤
│ 63871 │ Folder │ Zootopia (2016) 720p │ 0    │ 2016-07-31 03:41:05 EDT │
└───────┴────────┴──────────────────────┴──────┴─────────────────────────┘
```
As seen above, watchstate seems to have imported both the movie and the folder as separate items, with different IDs. The movie is listed as matched, and the folder is listed as unmatched.

Same exact media is also scanned into a Plex library, which is also added to watchstate as a backend. The plex backend does not list the folders as unmatched items.

**Basic report**

```
[ Basic Report ]

WatchState Version: 3bacbcf
PHP Version: 8.2.5
Timezone: America/New_York
Running in Container? Yes
Data Path: /config
Temp Path: /config
Database Migrated?: Yes
Has .env file? No
Is Tasks Runner working? Yes
Report Generated At: 2023-05-27T01:03:26+00:00

[ Backends ]

[ Emby ==> emby ]

Is backend URL HTTPS? No
Has Unique Identifier? Yes
Has User? Yes
Export Enabled? Yes
Time since last export? Never
Play state import enabled? Yes
Metadata only import enabled? No
Time since last import? 2023-05-27T01:00:45+00:00
Has webhook token? Yes
Is webhook match user id enabled? No
Is webhook match backend unique id enabled? No
Has custom options? Yes
{"ignore":"54394,212168,525569,472520,1803662"}
[ Plex ==> clplex ]

Is backend URL HTTPS? Yes
Has Unique Identifier? Yes
Has User? Yes
Export Enabled? Yes
Time since last export? 2023-05-26T21:31:02+00:00
Play state import enabled? Yes
Metadata only import enabled? Yes
Time since last import? 2023-05-27T01:00:48+00:00
Has webhook token? Yes
Is webhook match user id enabled? Yes
Is webhook match backend unique id enabled? Yes
Has custom options? Yes
{"IMPORT_METADATA_ONLY":true}
[ Emby ==> clemby ]

Is backend URL HTTPS? Yes
Has Unique Identifier? Yes
Has User? Yes
Export Enabled? Yes
Time since last export? 2023-05-26T21:31:02+00:00
Play state import enabled? Yes
Metadata only import enabled? Yes
Time since last import? 2023-05-27T01:00:48+00:00
Has webhook token? Yes
Is webhook match user id enabled? No
Is webhook match backend unique id enabled? No
Has custom options? Yes
{"IMPORT_METADATA_ONLY":true}
[ Plex ==> plex ]

Is backend URL HTTPS? Yes
Has Unique Identifier? Yes
Has User? Yes
Export Enabled? Yes
Time since last export? 2023-05-26T21:31:02+00:00
Play state import enabled? Yes
Metadata only import enabled? Yes
Time since last import? 2023-05-27T01:00:49+00:00
Has webhook token? Yes
Is webhook match user id enabled? Yes
Is webhook match backend unique id enabled? Yes
Has custom options? Yes
{"IMPORT_METADATA_ONLY":true,"ignore":"11,22,21,20,12"}
[ Tasks ]

[ Import ]

Is Task enabled? Yes
Which flags are used to run the task? -v
When the task scheduled to run at? 0 */1 * * *
When is the next scheduled run? 2023-05-27T02:00:00+00:00

[ Export ]

Is Task enabled? Yes
Which flags are used to run the task? -v
When the task scheduled to run at? 30 */1 * * *
When is the next scheduled run? 2023-05-27T01:30:00+00:00

[ Push ]

Is Task enabled? No

[ Backup ]

Is Task enabled? No

[ Prune ]

Is Task enabled? Yes
Which flags are used to run the task? -v
When the task scheduled to run at? 0 */12 * * *
When is the next scheduled run? 2023-05-27T04:00:00+00:00

[ Indexes ]

Is Task enabled? Yes
Which flags are used to run the task? -v
When the task scheduled to run at? 0 3 * * 3
When is the next scheduled run? 2023-05-31T07:00:00+00:00

[ Requests ]

Is Task enabled? Yes
Which flags are used to run the task? -v --no-stats
When the task scheduled to run at? */2 * * * *
When is the next scheduled run? 2023-05-27T01:04:00+00:00

[ Logs ]

[ /config/logs/app.20230526.log ]

app log file is empty or does not exists.

[ /config/logs/access.20230526.log ]

access log file is empty or does not exists.

[ /config/logs/task.20230526.log ]

[2023-05-26T21:01:11-04:00] NOTICE: SYSTEM: Finished waiting on [60] requests.
[2023-05-26T21:01:11-04:00] NOTICE: MAPPER: No changes detected.
┌─────────┬───────┬─────────┬────────┐
│ Type    │ Added │ Updated │ Failed │
├─────────┼───────┼─────────┼────────┤
│ Movie   │ 0     │ 0       │ 0      │
├─────────┼───────┼─────────┼────────┤
│ Episode │ 0     │ 0       │ 0      │
└─────────┴───────┴─────────┴────────┘

[ /config/logs/app.20230525.log ]

app log file is empty or does not exists.

[ /config/logs/access.20230525.log ]

access log file is empty or does not exists.

[ /config/logs/task.20230525.log ]

task log file is empty or does not exists.
```

**Additional context**
I'm using the latest stable Emby 4.7.12.0
Interestingly, my other emby server (clemby) only returns one movie folder when I run an unmatched report. That server is much newer. The one with the issue was set up several years ago.

**Comment by aptalca** [comment]
Wait, now that I go into the metadata manager on both emby servers and compare, I see that this is an emby issue where it lists both the folder and the movie inside it. The other server only lists the movies and not the folders except for that one.

I'll report it to emby and report back here. I wonder if it's due to some internal changes that happened to emby over the years.

**Comment by ArabCoders** [comment]
Hi, Thanks for your report, I personally use emby as well and i dont have problem at all. re-run the import with `-vvv --trace --context` it should give you more than enough information to go on. link the relevent info and then we can proceed.

> Wait, now that I go into the metadata manager on both emby servers and compare, I see that this is an emby issue where it lists both the folder and the movie inside it. The other server only lists the movies and not the folders except for that one.

afaik, emby and jellyfin clean after themselves if movies are moved or renamed. However sometimes there is still records in the db about it.

**Comment by aptalca** [comment]
It turns out, it was due to a couple of settings in Emby that are not in the gui. The defaults have changed over the years. My older server had different settings than the newer one, hence the different behavior.

I changed the settings for folder flattening, and after library scan and forced metadata refresh, all those folder items disappeared.

Then I did an import in watchstate and no more unmatched folders listed.

For anyone else with older servers who notice the same issue, the settings are:
1. `<CollapseVideoFolders>` tag in your programdata folder \config\system.xml
2. `<CollapseSingleItemFolders>` tag in your programdata folder \root\default\[YourMovieLibrary]\options.xml

Both need to be set to `true`

Here's the relevant forum post:
https://emby.media/community/index.php?/topic/118976-movie-library-has-the-movie-folders-added-as-library-items-as-well/#comment-1255542

**Comment by ArabCoders** [comment]
> It turns out, it was due to a couple of settings in Emby that are not in the gui. The defaults have changed over the years. My older server had different settings than the newer one, hence the different behavior.
> 
> 
> 
> I changed the settings for folder flattening, and after library scan and forced metadata refresh, all those folder items disappeared.
> 
> 
> 
> Then I did an import in watchstate and no more unmatched folders listed.
> 
> 
> 
> For anyone else with older servers who notice the same issue, the settings are:
> 
> 1. `<CollapseVideoFolders>` tag in your programdata folder \config\system.xml
> 
> 2. `<CollapseSingleItemFolders>` tag in your programdata folder \root\default\[YourMovieLibrary]\options.xml
> 
> 
> 
> Both need to be set to `true`
> 
> 
> 
> Here's the relevant forum post:
> 
> https://emby.media/community/index.php?/topic/118976-movie-library-has-the-movie-folders-added-as-library-items-as-well/#comment-1255542

Thanks for the update.
