### ISSUE TITLE
Plex Pass issue

### ISSUE THREAD

**Issue by ChrisPates** [ArabCoders/watchstate#32]
Hi, like the project, I've been meaning to explore this approach myself, as I have different plex servers in different location and want to keep all the users watch state sync.

Slightly problem, with the approach for plex. A user only gets access to the webhook capability, if they personally have a plex pass. This means, buying for every family member, also doesn't work for managed user.

The documentation is a little vague on whether the server owner's webhook is hit for shared users media.* appear to be yes for playback.started but not for the others. 

The plex-token is only available to the owner of the server and any **_viewCount_** retrieved via the api is for the uid 1 (the server owner account) which is going to make things a lot harder.

I'm not sure how you retrieve the **_viewCount_** for 'shared users' which includes plex account holder accessing the library as a shared library or managed users. The question is how do they authenticate, when logged in as these user types you can't retrieve the token as you don't have access to the xml info.

**Comment by ArabCoders** [comment]
Hi, 

Great questions, I'll try to answer to the best of my ability.

I personally haven't tested mutli-plex pass setup, but i assume it works like any other single user setup.

For managed users when you sign in as managed user you get a different x-plex-token than that of the server admin, and it's functions as both API key and user id, so effectively the information retrieved via this token solely belong to the user account it's even has different internal id in plex database afaik, For webhooks i haven't really tested if they are triggered via managed user or not. i should get to that at some point.

This tool only support single user right now, However it's possible to run mutli-user setup with different data directory
it's as easy as setting new `WS_DATA_PATH=/path php console command`

**Comment by ChrisPates** [comment]
I've been doing more digging, and by default only the 'owner' of the server has a token, but that account can switch to one of the shared/managed users https://python-plexapi.readthedocs.io/en/latest/modules/server.html .  

This may be the way to do it, in the servers.yml  declare as you do now but add a 'user identifier' if omitted then it default assumes the server owner account. So what is the user id? If you browse to a shared or managed user in the webUI (https://app.plex.tv/desktop/#!/settings/users-sharing/<12345678>) each has a unique id which (if you've put nginx proxy in front so you can read the raw requests) it appears to generate tokens based on client and session. Within plex itself (matching the scrobbler actions in the api requests to the entries in the plex debug logs it then shows the account id above. So it looks like is using the api behaviour from the docs 'access' the sharing/managed users.

**Comment by ArabCoders** [comment]
Hello, Thanks for digging deeper I'll have to do some tests to check out how it's implemented again,  

first time i tested it i logged in my admin account, and i was presented with different users, each time i selected different user it only gave me different x-plex-token, and when i used that against the API it did report only that user watch history. as far as i know the user id is not exposed via the API. but i'll dig deeper and see how it's function i'll also take look at how python-plexapi implements their switch user method.

**Comment by ArabCoders** [comment]
so from initial testing plex webhook does send events on managed accounts, and we already capture the USER_ID and USER_NAME using existing code, i implemented a fix to allow user_id to be checked if present in `servers.yaml` against the webhook payload user_id. 

so far, if you dont use managed users, admin is set to ID 1, if you add managed user it changes to external id, which is very confusing to be completely honest. I added a new `servers:remote` command to explore servers users list take look at it and see if works for you.

you have to switch to dev-latest tag though on docker. i plan to add docs about how to handle plex managed users in the feature.

Does that work for you?

**Comment by ChrisPates** [comment]
I’ll take a look, so when performing the initial sync from the servers it would also use the user id?

I have 3 users I want to ensure consistency across my plex servers, so I’m expecting to create a docker container for each, with the same config with the exception of the user_id attribute.

Sounds like you have made rapid progress, much appreciated. Happy to lend a hand on your project or just perform some testing. 

I hope you have cracked the multiple users sync challenges because all the other implementation I’ve seen only work for the server owner or require direct database access that means stopping the server which isn’t convenient. 

Kind regards,

Chris

m: +44 7482 123 244
e: ***@***.*** 

On 7 Mar 2022, at 10:51, Abdulmohsen ***@***.***> wrote:

﻿


so from initial testing plex webhook does send events on managed accounts, and we already capture the USER_ID and USER_NAME using existing code, i implemented a fix to allow user_id to be checked if present in servers.yaml against the webhook payload user_id.

so far, if you dont use managed users, admin is set to ID 1, if you add managed user it changes to external id, which is very confusing to be completely honest. I added a new servers:remote command to explore servers users list take look at it and see if works for you.

you have to switch to dev-latest tag though on docker. i plan to add docs about how to handle plex managed users in the feature.

Does that work for you?

**Comment by ArabCoders** [comment]
> snip

Right now multi user setup is complicated to implement and i wouldn't test it on your real database, unless you have backups, the idea is really simple

create as many instances as you want with different configs, each config points to a single user.

./user1:/config ./user2:/config etc, for each user you would have to log in as managed user get the token and use that as token in `servers.yaml` or via `console servers:edit --token '[plex_token]' -- plex_server_1`

for webhooks it will only function for one user at the moment i personally would choose the admin user, otherwise you can disable the webhook events and rely on cron import/export as explained in README.md if the tokens configured correctly it should work as intended. But to be sure make backup of your `Library/Application Support/Plex Media Server/Plug-in Support/Databases`

if you want to enable webhook for admin user you need to get the user ID to do so run

```bash
$ console servers:remote --list-users -- 'plex_server_1'
```
then update the config for that user with user_id
```bash
$ console servers:edit --user '[user_id]' -- 'plex_server_1'
```

Webhooks for multi users do work in emby and jellyfin as you can limit webhook for each specific user.

**Comment by ArabCoders** [comment]
> Getting the below:
> 
> ```
> docker exec -ti chris console servers:remote --list-users -- 'westlea'
> 
> In StreamHandler.php line 216:
>                                                                                                     
>   There is no existing directory at "/config%/logs" and it could not be created: Permission denied  
> ```
> 
> but the mount point for `/config`is owned by the WS_UID & WS_GID passed in the docker-compose and I don't see that source in your repo. 

it seems the path is not mounted correctly as indicated by the % in path `"/config%/logs"`, try creating the path locally then check again, if the issue still there set the env variable `WS_DATA_PATH=/config` manually docker-compose and see if it fixes the problem. and are you using `arabcoders/watchstate:dev-latest` container?

**Comment by ChrisPates** [comment]
Yes running with dev-latest, It's a bit weird because if skip that step and user the username as displayed in the webUi and then that works fine, updates the server.yml. Then running the state:import it pulls 1 watched record from each server (this is a purely test group of plex servers) so that seems to work.

**Comment by ChrisPates** [comment]
Its not throwing errors, it is just returning the watched state for the server owner and not the specified user.

**Comment by ArabCoders** [comment]
> Its not throwing errors, it is just returning the watched state for the server owner and not the specified user.

Oh i understand what you mean now

did make sure that the tokens are different for managed user and the admin one?
`

**Comment by ChrisPates** [comment]
but the only user with a token is the server owner.

**Comment by ArabCoders** [comment]
> but the only user with a token is the server owner.

I "just" tested it now on my plex server, once i switched to a managed user, the x-plex-token changed, to see that do the following.

1. https://app.plex.tv/desktop/
2. choose your main account first,
3. open developers toolbar, then go to Network and open the Fetch/XHR tab.
4. visit any link in your library
5. check the network log you will see a x-plex-token
6. Now, note that down
7. switch to your managed user account
8. do the steps from 3
9. check the token it should be different

Right now it's pretty manual, but i hope in the future i could do something like 

```bash
$ console servers:remote --list-users --with-tokens
```

**Comment by ChrisPates** [comment]
The only user you can obtain the token for is the server owner (admin) user ([official method](https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/)). You used to be able to retrieve them ([simplier scenario](https://github.com/jacobwgillespie/plex-sync/issues/87)) from the logs with certain debug features enabled but now they are just sub with a string of 'xxxxxx'.

Which is why I posted about how the python API library is supporting data access as a none admin user. The easiest way to see this is log into your plex server, and switch to any other user. Now try to follow the ([official method](https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/)). You can't, the only user able to access the xml view is the admin.

The follow discussion about [plex-sync](https://github.com/jacobwgillespie/plex-sync/issues/57) is the same problem we have here.

**Comment by ArabCoders** [comment]
I don't know what to tell you mate, im using plex Version 1.25.7.5604, and doing the steps i described up there i was able to obtain the managed user token easily and i tested it against the API and it responded correctly. could you humor me and try the steps and show me token you get when using managed user? you could replace few characters just to be safe.

**Comment by ChrisPates** [comment]
Okay, so going through the developer tooling, does get you a valid token for the shared/managed user but that really is messy. There has to be a better way?!

**Comment by ChrisPates** [comment]
No worries, there are some massive design flaws in the plex approach. Why they can't add a cluster concept and use http://litereplica.io/ methodology, for consistency and tweak their GDM announcements so the client sees the id of on network node, the name of the cluster with a single remote url for off-net access and fix it for everyone.

**Comment by ChrisPates** [comment]
So something worth noting, unlike the admin user the token for any other 'user' is server specific. However, I should be able to get cron based syncing running, for my users which is a quantum leap further than I had. 

Thank you for your efforts.

**Comment by ArabCoders** [comment]
> So something worth noting, unlike the admin user the token for any other 'user' is server specific. However, I should be able to get cron based syncing running, for my users which is a quantum leap further than I had.
> 
> Thank you for your efforts.

Indeed it seems to be server specific, but please do keep in mind it's still in alpha stage things could rapidly as i am still working on the code.

And no worries have nice day.

**Comment by ChrisPates** [comment]
Cool, I'll pull it into my dev setup and give a try.
