### ISSUE TITLE
[BUG] Jellyfin configuration stopped working - 11/11 update

### ISSUE THREAD

**Issue by IdefixRC** [ArabCoders/watchstate#360]
**Describe the bug**
Configration of jellyfin with URL and API key does not return unique identifier.
In addition error message if URL format is incorrect is missing from latest release. Rollback to [master-20231109-197d1cf] solves the issue.

**To Reproduce**
console config:add Jellyfin
add jellyfin configuration:
Server Unique Identifier: Empty string received

**Expected behavior**
Return unique identifier

**Comment by ArabCoders** [comment]
@IdefixRC Thanks for the bug report. It's fixed in dev branch, and will be pushed to master in few mins
