### ISSUE TITLE
[BUG] Webhook token Unify command is missing

### ISSUE THREAD

**Issue by defeatedbythecat** [arabcoders/watchstate#422]
**Describe the bug**

The documentation mentions using the unify command if you have multiple plex servers, however this command is not recognised in the console. 

`  Command "config:unify" is not defined.  
                                          
  Did you mean one of these?              
      config:add                          
      config:delete                       
      config:edit                         
      config:list                         
      config:manage                       
      config:view                         
                                          
`

**To Reproduce**

Just run the documented command

`docker exec -ti watchstate console config:unify plex `

**Expected behavior**

A unified token is created

**Comment by arabcoders** [comment]
Hi,
Thanks for reporting the issue, it was indeed removed a while back due to lack of use by people we will probably bring it back in different form, as of right now you can manually edit the `servers.yaml` file and pick one webhook token from the plex servers and replace the others with it.

**Comment by defeatedbythecat** [comment]
Just edited the file and it's now working perfectly, thank you!
