### ISSUE TITLE
No supported GUID

### ISSUE THREAD

**Issue by ikolsteren** [ArabCoders/watchstate#51]
Adding in Jellyfin server and getting error.  Have done the initial syncs. 

```
[2022-04-16T10:55:06.564015+00:00] logger.ERROR: JellyfinServer: No supported GUID was given. [] {"file":"/app/src/Libs/Servers/JellyfinServer.php","line":303} []
127.0.0.1 -  16/Apr/2022:10:55:06 +0000 "POST /index.php" 400
```

**Comment by ArabCoders** [comment]
Hi, Thanks for your report, im gonna need a webhook debug log to see the GUIDs your jellyfin is sending, from the log message it seems the payload did not contain any GUIDs. usually it will list them in in the brackets [].

also please make sure you followed https://github.com/ArabCoders/watchstate#jellyfin-free

**Comment by ikolsteren** [comment]
I did follow the instructions for the webhook for jellyfin.
I have both
```
            WS_LOGGER_FILE_ENABLE: "true"
            WS_WEBHOOK_DEBUG: "true"
```
Nothing in my webhooks folder - this was the compose I used yesterday and was working (I am using portainer for my compose and it errors if I don't have the true as a string with quotes)

**Comment by ArabCoders** [comment]
> WS_WEBHOOK_DEBUG:

Hmm.. could you try setting `WS_WEBHOOK_DEBUG: 1` instead and play anything in your jellyfin instance. if it's also not logging. then you can create new file in /config/config/ named .env and place WS_WEBHOOK_DEBUG=true

**Comment by ikolsteren** [comment]
Not winning - set both the environment and the .env file
No logging from either Jellyfin or Plex.   As soon as I hit play though I get the events though in the logs.
I had removed my folder earlier and then did a complete reconfig and the folders all got created when I made the new container :-(. 
the logs/app.log is being updated

**Comment by ArabCoders** [comment]
for example if you visit the webhook endpoint your via console 

curl -v http://localhost:8081/?apikey=foo do you get a json response ? 

im working right now on improving the the error messages to indicate exactly why the request failed. I'll have a new container  push within the hour. i just need to figure out how to customize caddy log messages.

**Comment by ikolsteren** [comment]
```
ubuntu@AdGuard1:/home/docker/watchstate/logs$ curl -v localhost:8081/?apikey=foo
*   Trying 127.0.0.1:8081...
* Connected to localhost (127.0.0.1) port 8081 (#0)
> GET /?apikey=foo HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Content-Type: application/json
< Server: Caddy
< Status: 401 Unauthorized
< Date: Sat, 16 Apr 2022 16:22:21 GMT
< Content-Length: 53
< 
* Connection #0 to host localhost left intact
{"error":true,"message":"Invalid API key was given."}
```

**Comment by ArabCoders** [comment]
Alright it seems the endpoint is working, I'll let you know once i have the new build out

**Comment by ArabCoders** [comment]
Ok, i have pushed new command to dump your environment, once you pull the new container, please run 

```bash
$ docker exec -ti watchstate console config:env
```

and post the output

**Comment by ikolsteren** [comment]
```
sudo docker exec -ti watchstate console config:env

                                                                                                                        
 Command "config:env" is not defined.       

```
Looking like maybe I have missed something?

**Comment by ArabCoders** [comment]
> ```
> sudo docker exec -ti watchstate console config:env
> 
>                                                                                                                         
>  Command "config:env" is not defined.       
> ```
> 
> Looking like maybe I have missed something?

the build is still running, give it few mins you can check in the action tab

**Comment by ikolsteren** [comment]
New the GitHub - the actions thing I didn't know
```
┌───────────────────────┬─────────────────┐
│ Key                   │ Value           │
├───────────────────────┼─────────────────┤
│ WS_LOGGER_FILE_ENABLE │ 1               │
│ WS_CRON_EXPORT        │ 1               │
│ WS_UID                │ 1000            │
│ WS_WEBHOOK_DEBUG      │ true            │
│ WS_GID                │ 1000            │
│ WS_CRON_IMPORT        │ 1               │
│ WS_TZ                 │ America/Toronto │
│ WS_CRON_PUSH          │ 1               │
```

**Comment by ArabCoders** [comment]
it seems the ENV is correct, and you try sending webhook event now and see what logs you get?

**Comment by ikolsteren** [comment]
No webhooks logs showing up for Jellyfin - just the 

Plex logged webhooks and I was able to manually push the updates
```
sudo docker exec -ti watchstate console state:push -vvv
[2022-04-16T18:14:02.399987+00:00] logger.NOTICE: Ignoring unRaid_Jellyfin - [The Curse of Oak Island - (9x3) - Stone Roadblock]. Not found in cache. [] []
[2022-04-16T18:14:02.403451+00:00] logger.NOTICE: Waiting on (1) (Stats Change) Requests. [] []
[2022-04-16T18:14:02.457902+00:00] logger.NOTICE: Finished waiting on (1) Requests. [] []
```
Back to sort of the error from before 
Had done the import on the jellyfin server earlier as well
```
sudo docker exec -ti watchstate console state:import --force-full --import-unwatched -vv --servers-filter unRaid_Jellyfin
[2022-04-16T18:13:06.610301+00:00] logger.NOTICE: Importing 'unRaid_Jellyfin' play state changes since beginning. [] []
[2022-04-16T18:13:06.861290+00:00] logger.NOTICE: Waiting on (7) HTTP Requests. [] []
[2022-04-16T18:13:19.143546+00:00] logger.NOTICE: Finished waiting HTTP Requests. [] []
[2022-04-16T18:13:19.143744+00:00] logger.NOTICE: Committing (1202) Changes. [] []
┌─────────┬───────┬─────────┬────────┐
│ Type    │ Added │ Updated │ Failed │
├─────────┼───────┼─────────┼────────┤
│ Movie   │ 1079  │ 0       │ 0      │
├─────────┼───────┼─────────┼────────┤
│ Episode │ 123   │ 0       │ 0      │
└─────────┴───────┴─────────┴────────┘
```
Something wonky on the Jellyfin side on both the manual and web hook side

**Comment by ArabCoders** [comment]
If the settings are correct, the only two possible ways for no logs is, 1 the api key is wrong thus no logs will be recorded for payload, or the payload itself is empty or wrong.

if you do docker logs -f watchstate

and hit play on jellyfin side, do you get an error in the log? like response_status: ... response_text: ...

**Comment by ikolsteren** [comment]
```
response_status: 401 - response_text: "API key is valid, User checks failed." - request_key: "a192d1b6ec2d2cb75b46ebd46a38bb2f" - http_request: "POST / HTTP/1.1":75 - user_ip: 192.168.50.16 - http_host: 192.168.50.200:8081 - user_agent: "Jellyfin-Server/10.7.7"
```
My Jellyfin is setup for multiple users as well
I have my Webhook checked for my user otherwise nothing gets sent at all - that seems to be the only variance from your instructions

**Comment by ArabCoders** [comment]
can you disable user check for jf and generate webhook log

**Comment by ikolsteren** [comment]
hope this is what you meant
```
unRaid_Jellyfin:
  type: jellyfin
  url: 'http://192.168.50.16:8096'
  token: 7bd5419cf34b491a82acbdc40905e05e
  uuid: a22205c8fd42461286248b5bc66279aa
  user: dae7e58e4f6c43808831fa11c1c0b5e2
  import:
    enabled: true
    lastSync: 1650132819
  export:
    enabled: true
  webhook:
    import: true
    push: true
    match:
      user: false
      uuid: true
    token: a192d1b6ec2d2cb75b46ebd46a38bb2f
  persist: {  }
```

```
[2022-04-16T18:47:13.832247+00:00] logger.ERROR: JellyfinServer: No supported GUID was given. [] {"file":"/app/src/Libs/Servers/JellyfinServer.php","line":303,"attributes":{"SERVER_ID":"a22205c8fd42461286248b5bc66279aa","SERVER_NAME":"Jellyfin Server","SERVER_VERSION":"10.7.7","USER_ID":"dae7e58e4f6c43808831fa11c1c0b5e2","USER_NAME":"Ian"}} []
127.0.0.1 -  16/Apr/2022:18:47:13 +0000 "POST /index.php" 400
response_status: 400 - response_text: "JellyfinServer: No supported GUID was given. []" - request_key: "a192d1b6ec2d2cb75b46ebd46a38bb2f" - http_request: "POST / HTTP/1.1":85 - user_ip: 192.168.50.16 - http_host: 192.168.50.200:8081 - user_agent: "Jellyfin-Server/10.7.7"
```

**Comment by ArabCoders** [comment]
> 

Nah, i mean the /config/webhooks/*.json file it should contain the payload from jellyfin it will help us diagnose both of the issues you are reporting the incorrect user match and "No supported GUID was given"

**Comment by ikolsteren** [comment]
Nothing from Jellyfin showing in that folder I have stuff from my two Plex servers but nothing from Jellyfin
Just restarted Jellyfin to see if that makes a difference.   The server is trying to send something based on the main logs
Not sure why.  Disabled both the user and uuid now
Did see this now in log
```
response_status: 200 - response_text: "JellyfinServer: Not allowed event [PlaybackStop]" - request_key: "f25c47e9ee928ae20d0aa0c700018458" - http_request: "POST / HTTP/1.1":5 - user_ip: 192.168.50.16 - http_host: 192.168.50.200:8081 - user_agent: "Jellyfin-Server/10.7.7"

```

**Comment by ArabCoders** [comment]
> "JellyfinServer: Not allowed event [PlaybackStop]"

That's clear things a bit, sorry it seems i forgot to update the code when i decided to split events. give it 30mins and a new build will be deployed I'll update you once the build is ready. After that you will be able to get the payload.

**Comment by ArabCoders** [comment]
ok new build is up please switch to dev-latest and try

**Comment by ikolsteren** [comment]
Ok just wiped everything and pulled the latest
Neither Plex or Jellyfin working 
```
127.0.0.1 -  16/Apr/2022:20:39:50 +0000 "POST /index.php" 401
response_status: 401 - response_text: "API key is valid, User checks failed." - request_key: "-" - http_request: "POST /?&apikey=8aa5707d2a301385080780dcc961d2a3 HTTP/1.1":75 - user_ip: 192.168.50.25 - http_host: 192.168.50.200:8081 - user_agent: "PlexMediaServer/1.26.0.5715-8cf78dab3"
[2022-04-16T20:39:52.529580+00:00] logger.ERROR: API key is valid, User checks failed. {"file":"/app/src/Libs/helpers.php","line":367,"attributes":{"SERVER_ID":"d7b5c5528d3172c2dde373e4936f0b7fa8598720","SERVER_NAME":"Ian's Media Server","SERVER_VERSION":"1.26.0.5715-8cf78dab3","USER_ID":1,"USER_NAME":"Ian_and_George"}} []
127.0.0.1 -  16/Apr/2022:20:39:52 +0000 "POST /index.php" 401
response_status: 401 - response_text: "API key is valid, User checks failed." - request_key: "-" - http_request: "POST /?&apikey=8aa5707d2a301385080780dcc961d2a3 HTTP/1.1":75 - user_ip: 192.168.50.25 - http_host: 192.168.50.200:8081 - user_agent: "PlexMediaServer/1.26.0.5715-8cf78dab3"
[2022-04-16T20:40:04.969820+00:00] logger.ERROR: JellyfinServer: No supported GUID was given. [] {"file":"/app/src/Libs/Servers/JellyfinServer.php","line":305,"attributes":{"SERVER_ID":"a22205c8fd42461286248b5bc66279aa","SERVER_NAME":"Jellyfin Server","SERVER_VERSION":"10.7.7","USER_ID":"dae7e58e4f6c43808831fa11c1c0b5e2","USER_NAME":"Ian"}} []
```

I had tested before wiping and didn't work 

All servers are set to:
```
    match:
      user: true
      uuid: true
```

**Comment by ikolsteren** [comment]
And to confirm this is the webhook for Plex with both the ?&
http://IP:8081/?&apikey=##########

**Comment by ArabCoders** [comment]
Indeed as it's showing in the logs the api key is valid, for now, also please double check "Send All Properties (ignores template)" is ticked in the webhook payload in jellyfin.

if it's ticked, then disable the match: user i want to see what user_id being reported.

**Comment by ArabCoders** [comment]
Ok, i created a test environment and i was able to produce your errors. by unchecking "Send All Properties (ignores template)"
i was getting exactly the same errors as you are reporting. So, please go again and check that "Send All Properties (ignores template)" is checked. and click save.

**Comment by ikolsteren** [comment]
The check is there and I recreated the webhook to make sure
unchecked the match user and this is in the log
```
[2022-04-16T21:19:21.255714+00:00] logger.ERROR: JellyfinServer: No supported GUID was given. [] {"file":"/app/src/Libs/Servers/JellyfinServer.php","line":305,"attributes":{"SERVER_ID":"a22205c8fd42461286248b5bc66279aa","SERVER_NAME":"Jellyfin Server","SERVER_VERSION":"10.7.7","USER_ID":"dae7e58e4f6c43808831fa11c1c0b5e2","USER_NAME":"Ian"}} []
127.0.0.1 -  16/Apr/2022:21:19:21 +0000 "POST /index.php" 400
response_status: 400 - response_text: "JellyfinServer: No supported GUID was given. []" - request_key: "fa3ed9f2cbd2465f637db75bf7a3077b" - http_request: "POST / HTTP/1.1":85 - user_ip: 192.168.50.16 - http_host: 192.168.50.200:8081 - user_agent: "Jellyfin-Server/10.7.7"

```
Still nothing in the webhooks folder

**Comment by ArabCoders** [comment]
Do you have discord?

**Comment by ikolsteren** [comment]
Yes I do 
See if I can add a screen shot from Jellyfin
<img width="523" alt="Screen Shot 2022-04-16 at 5 23 14 PM" src="https://user-images.githubusercontent.com/6809510/163691717-fbb3d1b1-e1bc-4712-b750-b069562e2b13.png">

**Comment by ArabCoders** [comment]
please add me "Cyclowned#8388" and we can speed this up xD

**Comment by ArabCoders** [comment]
as we discussed in discord it seems this bug related to no external IDs "GUIDs" being reported via jellyfin.
