### ISSUE TITLE
Ignoring a library with an ID that is an integer throws an error

### ISSUE THREAD

**Issue by Jacob-Lasky** [ArabCoders/watchstate#76]
Thanks for this tool, it is EXACTLY what I was looking for. I'm just tinkering around with it and have run into this issue:

![bad plex](https://user-images.githubusercontent.com/6790237/164993775-5fdae51d-cca5-4cd9-b6d2-d569a35717b8.png)

If I add a trailing `,` to the library ID, then it ignores it fine:
![good plex](https://user-images.githubusercontent.com/6790237/164993940-3644dacc-3287-439e-a482-c8048efe7445.png)

Here is an example of it working great with Jellyfin, where the library IDs are UUIDs:
![good jellyfin](https://user-images.githubusercontent.com/6790237/164993813-062a2a7d-81ff-41aa-8546-4a34ba543edc.png)

**Comment by ArabCoders** [comment]
Thanks, i pushed new fix should be ready within 30min,

**Comment by Jacob-Lasky** [comment]
@ArabCoders thank you!

**Comment by ArabCoders** [comment]
@Jacob-Lasky Np, and please do note you dont have to ignore unsupported library. they are ignored automatically.  if it says unsupported that mean it will auto ignore it as well.
