### ISSUE TITLE
Two-way sync prioritizes watched over unwatched

### ISSUE THREAD

**Issue by Jacob-Lasky** [ArabCoders/watchstate#78]
Not sure if I'm missing / not understanding something, but I just wanted to make this ticket so that it's stated explicitly!

**Current behavior**:
When marking something as unwatched in Plex (or Jellyfin), the item becomes marked as watched in Plex (or Jellyfin) after syncing. This seems to happen because the item is still marked as watched in Jellyfin (or Plex).

**Expected behavior**:
When marking something as unwatched in Plex or Jellyfin, I expect the item to be unwatched in both after syncing.

**Example**:
Both movies are watched in both Plex and Jellyfin
![watched in Plex](https://user-images.githubusercontent.com/6790237/164996421-c6f6f5d4-c8c6-40e5-90e9-f304c0719c52.png)

![watched in Jellyfin](https://user-images.githubusercontent.com/6790237/164996428-e3d8ea5e-10cd-4378-b61c-3bd796754a83.png)

I mark "3 Idiots" as unwatched in Plex and "6 Underground" as unwatched in Jellyfin
![unwatched 3 idiots](https://user-images.githubusercontent.com/6790237/164996440-4d5473f3-7052-47fd-9cab-6b42cc427ba4.png)
![unwatched 6 underground](https://user-images.githubusercontent.com/6790237/164996452-269b2263-dc82-4e97-ba5e-c8bfed227aab.png)

Now, I run the import command:
```
docker exec -ti watchstate-Jake-Monica console state:import -vrm
```
and then the export command:
```
docker exec -ti watchstate-Jake-Monica console state:export -vrm
```

I expect both movies to be marked as "unwatched" because that was the most recent state change. However, both movies are now marked as "watched" in both Plex and Jellyfin
![watched in Plex](https://user-images.githubusercontent.com/6790237/164996421-c6f6f5d4-c8c6-40e5-90e9-f304c0719c52.png)

![watched in Jellyfin](https://user-images.githubusercontent.com/6790237/164996428-e3d8ea5e-10cd-4378-b61c-3bd796754a83.png)

**Comment by TechPerplexed** [comment]
Wow :) I came here to create a similar ticket, and here you are and said it better than I ever could. I absolutely second this request, I would like stuff that I mark unwatched on one to be marked unwatched on all services. Thanks for (hopefully) considering this, @ArabCoders 😄

**Comment by ArabCoders** [comment]
Hi, lets try to clear things up a bit, the behavior depends on if you are using webhooks or not.

For webhook enabled servers > jellyfin, marking item as watch/unwatched does trigger webhook event,  sadly thats not true for plex, please does not trigger an event, i even opened feature request [here](https://forums.plex.tv/t/send-webhooks-events-for-mark-as-played-unplayed/787736), it just seems poeple are not interested. 

On the Task  scheduler side, right now tasks does not sync marked as unwatched items, as the flag is missing in the task definition, i have to come up with a way to allow it to be configured such that you can import unwatched episodes via tasks, and the export state does not override watch state unless the date on the object is older than what's recorded in the local database unless you use --ignore-date flag.

Anyway I'll come up with a environment variable to allow you to import unwatched.

**Comment by Jacob-Lasky** [comment]
@ArabCoders you're describing exactly what I want to see! I'm not using webhooks, so these are scheduled tasks.

> and the export state does not override watch state unless the date on the object is older than what's recorded in the local database

That was my intuition on how it would work. Thanks for a fast response :) Absolutely loving this tool!

**Comment by ArabCoders** [comment]
In 30mins pull the new container and set env: `WS_CRON_IMPORT_UNWATCHED` to `1` it should trigger unwatched import.

**Comment by ArabCoders** [comment]
The build is out. Please try it out and report back if you are facing any problems.

Thanks for your suggestions.

**Comment by TechPerplexed** [comment]
Working like a charm! I just tested it with all three (marking stuff unwatched) and it synced back to all the others. Thank you so much for your prompt implementation!
