### ISSUE TITLE
Sync currently playing item progress

### ISSUE THREAD

**Issue by binarygeek119** [ArabCoders/watchstate#99]
is it possible to sync emby's play state of a video to plex.
i use posterr and movienowapp but they only supports plex.
i have plex setup for posterr to pull somthing from.
but the play state doesnt work cause i play from emby.
if plex could mirror any play state emby does it would work.
im hoping that this could be my answer for this.

**Comment by ArabCoders** [comment]
Hi, Thank you for your request, I am not sure if it's possible to sync the play state from different media servers, I have to investigate this further, right now we are focusing on completing the database redesign #98 once that done I'll see if it's possible sync play timeline.

**Comment by ArabCoders** [comment]
Hi, i moved this issue to #130 as im merging all futures requests/plans there. I'll be updating this issue in the future if we can get this one going.
